release NetCDF file resources
castelao/oceansdb pull request #22
Opened 2023-02-17 06:50 UTC by electricsam

NetCDF files are opened, but never closed.  These changes allow database classes to be used with PEP-343, the "with" statement.

2023-02-17 16:51 UTC, castelao commented
@electricsam, thanks ! I'll review it tonight, maybe tomorrow. One step ahead, please add yourself in the `.zenodo` and the bottom of `AUTHORS.rst`.

2023-02-17 19:27 UTC, electricsam commented
@castelao Just an FYI, there are still resource issues with NetCDF, but it is not with this code.  There is a memory leak in the underlying C library, that is pending resolution.

https://github.com/Unidata/netcdf4-python/issues/1021
https://github.com/Unidata/netcdf-c/issues/2626

2023-02-19 21:41 UTC, castelao requested changes
Thanks!!

There is a conflict with the version definition. Look at my comments below. Also, please update with the changes I did upstream so it can run all the tests. Let me know if you would like help to do that.

2023-02-19 21:41 UTC, castelao commented on VERSION
> +version='0.8.15'
@electricsam , please undo this version bump. The version now is dynamically updated, so we don't need to change it manually anymore. Thanks!

2023-02-19 21:41 UTC, castelao commented on oceansdb/__init__.py
> +__version__ = '0.8.15'
Same here. Undoing this should resolve the conflict.

2023-02-21 14:03 UTC, electricsam commented
@castelao I reverted the version bump

2023-02-21 16:05 UTC, castelao approved these changes

2023-02-21 16:06 UTC, castelao commented
@electricsam , thank you! I'll release a new version later today.

2023-02-21 16:06 UTC, merged